name: Run Telegram Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        env:
          BOT_TOKEN: ${{ 8451058976:AAGl8EDYJg-zNUs2lpfZc_vqpt-__DKJXYs }}
        run: node index.js
